package com.qrscanmax.core.domain.model

import java.time.Instant

/**
 * Represents a single entry in the user's scan/generation history.
 *
 * History records are persisted in an encrypted Room database (SQLCipher) and
 * displayed in reverse-chronological order on the History tab. Records can be
 * marked as favorites for quick access and filtered by date range or search query.
 *
 * This is the domain-layer representation. The data layer maps this to/from
 * the Room entity with appropriate type converters.
 *
 * @property id Unique identifier, auto-generated by Room. Defaults to 0 for new records.
 * @property contentType The classified type of the scanned/generated content.
 * @property rawContent The raw string content of the barcode/QR code.
 * @property displayTitle A human-readable title derived from the content
 *   (e.g., domain name for URLs, SSID for WiFi, contact name for vCards).
 * @property timestamp The instant when the scan or generation occurred.
 * @property source Whether this record was created by scanning or generating.
 * @property isFavorite Whether the user has marked this record as a favorite. Defaults to false.
 * @property thumbnailPath Optional file path to a cached thumbnail of the generated QR code image.
 *
 * @see RecordSource
 * @see ContentType
 */
data class HistoryRecord(
    val id: Long = 0,
    val contentType: ContentType,
    val rawContent: String,
    val displayTitle: String,
    val timestamp: Instant,
    val source: RecordSource,
    val isFavorite: Boolean = false,
    val thumbnailPath: String? = null
)

/**
 * Indicates how a [HistoryRecord] was created.
 */
enum class RecordSource {
    /** The record was created by scanning a barcode/QR code using the camera or album import. */
    SCAN,

    /** The record was created by generating a new QR code in the Generator feature. */
    GENERATED
}
